/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.marquis.wordcounter;

import java.util.ArrayList;

/**
 *
 * @author marquis
 */
public class startFrame extends javax.swing.JFrame {

    private final String tester = "Scotty is a man and Scotty likes bacon. I also like bacon. Everyone likes bacon.";
    private final String RGX = "[\\W]"; //regex to exclude all non letters/numbers.
    
    
    // I Want to exclude numbers and include apostrophes.
    
    /** Creates new form startFrame */
    public startFrame() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        ArrayList<word> tst = new ArrayList<>();
        tst.add(new word("beta"));
        tst.add(new word("kilt", 5));
        tst.add(new word("listen", 2));
        tst.add(new word("fahrenheit"));
        tst.add(new word("charlie", 6));
        tst.add(new word("delta", 3));
        tst.add(new word("hotel", 7));
        tst.add(new word("nautical", 4));
        tst.add(new word("item", 2));
        tst.add(new word("jerry", 3));
        tst.add(new word("alpha"));
        tst.add(new word("moment", 10));
        tst.add(new word("omniscient"));
        tst.add(new word("powerful"));
        tst.add(new word("epsilon"));
        tst.add(new word("grand"));
        wordList tstr = new wordList(tst);
        System.out.println(tstr.listToString());
        tstr.mergeSort(0, tst.size()-1, false);
        System.out.println(tstr.listToString());
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(startFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(startFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(startFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(startFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new startFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

}
